name: Deliver Action
description: Enhanced composite action for Deliver stage
inputs: {}
runs:
  using: composite
  steps:
  - name: Run command 1
    run: pyinstaller --onefile sources/add2vals.py
    shell: bash
