name: CI
'on':
  workflow_dispatch:
  push:
    branches:
    - master
    - main
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:2-alpine
    steps:
    - uses: actions/checkout@v4
    - name: Install bash
      run: apk add --no-cache bash
    - name: Run Build
      uses: ./.github/actions/build
  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: python:3.9-slim
    steps:
    - uses: actions/checkout@v4
    - name: Install pytest
      run: pip install pytest
    - name: Run Test
      uses: ./.github/actions/test
  deliver:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: python:3.9-slim
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y binutils
        pip install pyinstaller
    - name: Run Deliver
      uses: pyinstaller --onefile sources/add2vals.py
    
      
