name: CI
'on':
  workflow_dispatch:
  push:
    branches:
    - master
    - main
  pull_request: {}
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:2-alpine
    steps:
    - uses: actions/checkout@v4
    - name: Run Build
      uses: ./.github/actions/build
      shell: sh
  test:
    runs-on: ubuntu-latest
    container:
      image: qnib/pytest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Run Test
      uses: ./.github/actions/test
      shell: sh  
  deliver:
    runs-on: ubuntu-latest
    container:
      image: cdrx/pyinstaller-linux:python2
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Run Deliver
      uses: ./.github/actions/deliver
      shell: sh
      
